CREATE TABLE IF NOT EXISTS products (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    slug VARCHAR(180) NOT NULL UNIQUE,
    description TEXT NOT NULL DEFAULT '',
    price NUMERIC(10, 2) NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'USD',
    category VARCHAR(100) NOT NULL,
    style VARCHAR(100) NOT NULL DEFAULT '',
    theme VARCHAR(100) NOT NULL DEFAULT '',
    orientation VARCHAR(50) NOT NULL DEFAULT '',
    size VARCHAR(50) NOT NULL DEFAULT '',
    image_url TEXT NOT NULL DEFAULT '',
    thumbnail_url TEXT NOT NULL DEFAULT '',
    stock_quantity INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

INSERT INTO products (
    title,
    slug,
    description,
    price,
    currency,
    category,
    style,
    theme,
    orientation,
    size,
    image_url,
    thumbnail_url,
    stock_quantity,
    is_active
) VALUES
(
    'Golden Abstract Canvas',
    'golden-abstract-canvas',
    'Warm abstract wall art with gold and white texture.',
    129.99,
    'USD',
    'Canvas',
    'Abstract',
    'Modern',
    'Landscape',
    '24x36 in',
    'https://example.com/images/golden-abstract-canvas.jpg',
    'https://example.com/images/golden-abstract-canvas-thumb.jpg',
    12,
    TRUE
),
(
    'Blue Ocean Print',
    'blue-ocean-print',
    'Calm ocean inspired print for living room or office walls.',
    59.99,
    'USD',
    'Print',
    'Minimal',
    'Nature',
    'Portrait',
    '18x24 in',
    'https://example.com/images/blue-ocean-print.jpg',
    'https://example.com/images/blue-ocean-print-thumb.jpg',
    25,
    TRUE
),
(
    'City Night Poster',
    'city-night-poster',
    'Dark city skyline poster with a clean contemporary look.',
    39.99,
    'USD',
    'Poster',
    'Photography',
    'Urban',
    'Landscape',
    '16x20 in',
    'https://example.com/images/city-night-poster.jpg',
    'https://example.com/images/city-night-poster-thumb.jpg',
    40,
    TRUE
)
ON CONFLICT (slug) DO NOTHING;
